version: '3.1'
services:
  db:
    image: mysql
    container_name: db_calculafrete
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_calculafrete:/var/lib/mysql

volumes:
  db_calculafrete: